### ISSUE TITLE
Gaps between squares & missing squares

### ISSUE THREAD

**Issue by fractalbach** [fractalbach/gamenet#17] opened 2018-03-11 10:47 UTC
![clips](https://user-images.githubusercontent.com/32124562/37252472-6196bac4-24de-11e8-92a4-862d4976bab0.png)

* Square holes around the sides
* Gaps in between squares

**Comment by TryExceptElse** [comment] 2018-03-11 20:47
These are unrelated issues.
The former is caused by three.js not updating tile radius for purpose of determining if it needs to be drawn to screen
The latter is caused by the additional vertices on higher-detail tiles not lining up with the edges of lower detail tiles. Tile skirts are implemented already, but are currently not properly shaded.

**Comment by TryExceptElse** [comment] 2019-06-08 07:07
The second of these is now resolved by recomputing the bounding box upon geometry changes.

**Comment by TryExceptElse** [comment] 2019-06-08 22:59
Closed by fc04574f747bd4edce08748b9948a14bdeb5522e

**Closed by TryExceptElse** 2019-06-08 22:59 UTC
